sia:
  siteplan-url: "https://www.sia.aviation-civile.gouv.fr/plandesite"
  auto-version:
    enabled: true


vac-atlas:
  e-aip-version: eAIP_20_APR_2023
  base-url: https://www.sia.aviation-civile.gouv.fr/dvd/${vac-atlas.e-aip-version}/Atlas-VAC
  airport-list-js-url: ${vac-atlas.base-url}/Javascript/AeroArraysVac.js
  helipad-list-js-url: ${vac-atlas.base-url}/Javascript/AeroArraysVach.js
  airport-card-url-template: ${vac-atlas.base-url}/PDF_AIPparSSection/VAC/AD/AD-2.{code}.pdf
  helipad-card-url-template: ${vac-atlas.base-url}/PDF_AIPparSSection/VACH/AD/AD-3.{code}.pdf

aixm:
  import:
    sources:
#      - uri: "file:data/aixm/export_xml_bd_sia_2023-05-18-a3"
#        description: "SIA dataset from 2023-05-18"
#      - uri: "file:data/aixm/export_xml_bd_sia_2023-06-15-x1"
#        description: "SIA dataset from 2023-06-15"
      - uri: "file:data/aixm/export_xml_bd_sia_2023-07-13-b5"
        description: "SIA dataset from 2023-07-13"
    parse-sia-export: true

  update:
    enabled: true
    initial-delay: 0
    fixed-delay: 60

zicad:
  import:
    sources:
      - uri: "https://www.geoportail.gouv.fr/depot/layers/ORTHOIMAGERY.ORTHOPHOS.RESTRICTEDAREAS/kml/Arrete_ZICAD_01-2023.kml"
        description: "ZICAD dataset from 2023-03-02"
#      - uri: "https://www.data.gouv.fr/fr/datasets/r/0a4cfab5-465a-45e2-bc83-ad65c299bc90"
#        description: "ZICAD dataset from 2023-03-02"

  update:
    enabled: true
    initial-delay: 0
    fixed-delay: 60

altitude-service:
  type: "ign"
  ign:
    rest-service-url: 'https://data.geopf.fr/altimetrie/calcul/alti/rest/elevation.json'
    data-resource-id: 'ign_rge_alti_wld'

spring:
  cloud:
    refresh:
      enabled: true

cache:
  rate-limit-buckets:
    enabled: true
    maximum-size: 10000

  altitude:
    enabled: true
    maximum-size: 10000
    expire-after-access: "10m"

  proximity-info:
    enabled: true
    maximum-size: 500
    expire-after-access: "10m"

logging:
  level:
    com.mass: DEBUG

server:
  port: 8077
  servlet:
    application-display-name: 'Flightplan API'
    context-path: "/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "health, beans, mappings"
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
    caches:
      enabled: true
    beans:
      enabled: true
    mappings:
      enabled: true

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*/api.*/proximity.*
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: 12
              time: 1
              unit: minutes
      metrics:
        enabled: true
        types: REJECTED_COUNTER

  default-metric-tags:
    - key: IP
      expression: getRemoteAddr()
      types: REJECTED_COUNTER
