sia:
  siteplan-url: "https://www.sia.aviation-civile.gouv.fr/plandesite"
  auto-version:
    enabled: true


vac-atlas:
  e-aip-version: eAIP_20_APR_2023
  base-url: https://www.sia.aviation-civile.gouv.fr/dvd/${vac-atlas.e-aip-version}/Atlas-VAC
  airport-list-js-url: ${vac-atlas.base-url}/Javascript/AeroArraysVac.js
  helipad-list-js-url: ${vac-atlas.base-url}/Javascript/AeroArraysVach.js
  airport-card-url-template: ${vac-atlas.base-url}/PDF_AIPparSSection/VAC/AD/AD-2.{code}.pdf
  helipad-card-url-template: ${vac-atlas.base-url}/PDF_AIPparSSection/VACH/AD/AD-3.{code}.pdf

  ignored-airports: ['LFRJ', 'LFRL']
  ignore-runway-extraction-errors: ['LFIP', 'LFHU', 'LFMX', 'LFNZ', 'LFTB']

  pdf-extraction:
    type: pdftotext
    executor:
      core-pool-size: 6
      max-pool-size: 6
      thread-name-prefix: pdf-conversion
    timeout: 2m
    keep-files: true
    ocr-dpi: 480

  update:
    enabled: true
    cron: "0 0 4 * * *"  # 4AM every day
    refresh-when-older-than: 1d
    max-errors: 0

altitude-service:
  type: "ign"
  ign:
    rest-service-url: 'https://wxs.ign.fr/calcul/alti/rest/elevation.json'

spring:
  cloud:
    refresh:
      enabled: true

logging:
  level:
    com.mass: TRACE
    org.apache.pdfbox.pdmodel.font.PDSimpleFont: ERROR