sia:
  siteplan-url: "https://www.sia.aviation-civile.gouv.fr/plandesite"
  auto-version:
    enabled: true


vac-atlas:
  e-aip-version: eAIP_20_APR_2023
  base-url: https://www.sia.aviation-civile.gouv.fr/dvd/${vac-atlas.e-aip-version}/Atlas-VAC
  airport-list-js-url: ${vac-atlas.base-url}/Javascript/AeroArraysVac.js
  helipad-list-js-url: ${vac-atlas.base-url}/Javascript/AeroArraysVach.js
  airport-card-url-template: ${vac-atlas.base-url}/PDF_AIPparSSection/VAC/AD/AD-2.{code}.pdf
  helipad-card-url-template: ${vac-atlas.base-url}/PDF_AIPparSSection/VACH/AD/AD-3.{code}.pdf

aixm:
  import:
    sources:
      - "file:aixm/export_xml_bd_sia_2023-04-20-p2"
      - "file:aixm/export_xml_bd_sia_2023-05-18-a3"
      - "file:aixm/export_xml_bd_sia_2023-06-15-x1"
    parse-sia-export: true

  update:
    enabled: true
    initial-delay: 0
    fixed-delay: 60

altitude-service:
  type: "ign"
  ign:
    rest-service-url: 'https://wxs.ign.fr/calcul/alti/rest/elevation.json'

spring:
  cloud:
    refresh:
      enabled: true
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=1h

logging:
  level:
    com.mass: DEBUG

server:
  port: 8080
  servlet:
    application-display-name: 'Flightplan API'
    context-path: "/"

management:
  endpoints:
    web:
      exposure:
        include: "metrics, health, caches"
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
    caches:
      enabled: true

bucket4j:
  enabled: true
  cache-to-use: jcache
  filters:
    - cache-name: rate-limit-buckets
      url: .*/api.*/proximity.*
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: 6
              time: 1
              unit: minutes
      metrics:
        enabled: true
        types: REJECTED_COUNTER

  default-metric-tags:
    - key: IP
      expression: getRemoteAddr()
      types: REJECTED_COUNTER
